### ISSUE TITLE
[Enhancement] Shortcuts for a SEQUENCE of clicks...

### ISSUE THREAD

**Issue by timh-86** [mywebshortcuts/mywebshortcuts#72]
Not sure if this is technically feasible, but it would be awesome if My Web Shortcuts could allow shortcuts for SEQUENCES of clicks... 

For example: "Press Element" > menu opens > "Then Press option in menu" > new menu opens "Press final menu item"

Would be a real time saver! :)

**Comment by prakhartiwari0** [comment]
Hey @timh-86, thanks for sharing your idea here. I guess you didn't check this so let me tell you. This feature is very demanded, and I actually planned in the very beginning, but it would have complicated the project too much resulting in unnecessary delays, so I didn't built it. 
I am working on a lot of features and changes recently so expect to get this feature in a few days, hope it helps you ;) 

You can checkout [this huge list of features that will added in this extension](https://github.com/mywebshortcuts/mywebshortcuts/discussions/32). 
Also, if you like, you can vote for the feature you want to be added [here](https://mywebshortcuts.canny.io/feature-requests). 

And because [there's an issue already open for this feature](https://github.com/mywebshortcuts/mywebshortcuts/issues/68), I will have to close this to avoid confusions.

Thanks for your time!
Take care <3
